---
apiVersion: v1
kind: Service
metadata:
  name: forecast
spec:
  type: NodePort
  selector:
    app: forecast
  ports:
    - name: http
      port: 8980
      protocol: TCP
      targetPort: 8980
   # - name: https
   #   port: 8443
   #   protocol: TCP
   #   targetPort: 443
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222
    - 192.168.0.223
    - 192.168.0.224
