---
apiVersion: v1
kind: Secret
metadata:
  name: forecast-appsettings-json
type: Opaque
data:
  forecast-appsettings.Production.json: ewogICJBY2N1V2VhdGhlciI6IHsKICAgICJBUElLZXkiOiAiQU1ZRERYN0JJUnppN0xReWtXcTI2bnJCYXdLSjJib2kiLAogICAgIkxvY2F0aW9uS2V5IjogIjIxNzI5MjYiCiAgfQp9Cg==