---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: power-consumption-optimizer
  labels:
    app: power-consumption-optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: power-consumption-optimizer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: power-consumption-optimizer
    spec:
      containers:
        - name: forecast
          imagePullPolicy: "Always"
          image: docker.io/styxut/forecast:dev
          ports:
            - containerPort: 8980
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          # readinessProbe:
          #   httpGet:
          #     path: /api/Forecast/HealthCheck
          #     port: 8980
          #   initialDelaySeconds: 10 
          #   periodSeconds: 120
          volumeMounts:
          - name: forecast-appsettings-volume
            mountPath: "/app/forecast-appsettings.Production.json"
            subPath: "forecast-appsettings.Production.json"
        - name: power-consumption-optimizer
          imagePullPolicy: "Always"
          image: styxut/powerconsumptionoptimizer:dev
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          volumeMounts:
          - name: pco-appsettings-volume
            mountPath: "/app/appsettings.Production.json"
            subPath: "appsettings.Production.json"
      volumes:  
      - name: forecast-appsettings-volume
        configMap:
          name: forecast-cm
          items:
          - key: forecast-appsettings.Production.json
            path: forecast-appsettings.Production.json
      - name: pco-appsettings-volume
        configMap:
          name: pco-cm  
          items:
          - key: appsettings.Production.json
            path: appsettings.Production.json
